---
title: "Project4"
author: "Lala Rukh"
date: '2022-04-20'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(DiagrammeR)
```

```{r}
 Plot_1 <- grViz(diagram = "digraph flowchart {
      # define node aesthetics
      node [fontname = Arial, shape = oval, color = Lavender, style = filled]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
      tab6 [label = '@@6']
      tab7 [label = '@@7']
      tab8 [label = '@@8']
      tab9 [label = '@@9']
      tab10 [label = '@@10']
      tab11 [label = '@@11']
      tab12 [label = '@@12']
      tab13 [label = '@@13']
      tab14 [label = '@@14']
      tab15 [label = '@@15']
      tab16 [label = '@@16']
      tab17 [label = '@@17']
      tab18 [label = '@@18']
      tab19 [label = '@@19']
      tab20 [label = '@@20']
      tab21 [label = '@@21']
      tab22 [label = '@@22']
      tab23 [label = '@@23']
      tab24 [label = '@@24']
      tab25 [label = '@@25']
      tab26 [label = '@@26']
      tab27 [label = '@@27']
      tab28 [label = '@@28']
# set up node layout
      tab1 -> tab2;
      tab2 -> tab3;
      tab3 -> tab4;
      tab2 -> tab5;
      tab5 -> tab6;
      tab6 -> tab7;
      tab7 -> tab8; 
      tab8 -> tab9;
      tab9 -> tab10;
      tab8 -> tab11;
      tab11 -> tab12;
      tab6 -> tab13;
      tab13 -> tab14;
      tab14 -> tab15; 
      tab15 -> tab16;
      tab16 -> tab17;
      tab17 -> tab18;
      tab16 -> tab19;
      tab19 -> tab20;
      tab14 -> tab21;
      tab21 -> tab 22;
      tab22 -> tab23;
      tab23 -> tab24;
      tab24 -> tab25;
      tab25 -> tab26;
      tab22 -> tab27; 
      tab27 -> tab28
      }
[1]: 'Convergence Test'
      [2]: 'Test for Divergence (lim n-infinity=0?)'
      [3]: 'No'
      [4]: 'sum an diverges'
      [5]: 'Yes'
      [6]: 'P-series: Does an= 1/n^p, n greater than equal to 1?'
      [7]: 'Yes'
      [8]: 'Is p greater than 1?' 
      [9]: 'Yes'
      [10]: 'sum an converges' 
      [11]: 'No'
      [12]: 'sum an diverges'
      [13]: 'No'
      [14]: 'Geometric Series: Does an = a^(r-1), n greater than equal to 1'
      [15]: 'Yes'
      [16]: 'Is abs(r) less than 1?'
      [17]: 'Yes'
      [18]: 'sum^inf_n=1 an = a/(1-r)'
      [19]: 'No'
      [20]: 'sum an diverges' 
      [21]: 'No'
      [22]: 'Alt Srs Test: an=(-1)^n b_n or an=(-1)^(n-1)b_n, b_n,0?'
      [23]: 'Yes'
      [24]: 'is b_(n+1) less than greater to bn and lim as n approaches infinity bn =0'
      [25]: 'Yes'
      [26]: 'sum an converges' 
      [27]: 'No'
      [28]: 'Try one of the following'
      
")



```

```{r}
Plot_2 <- grViz(diagram = "digraph flowchart {
      # define node aesthetics
      node [fontname = Arial, shape = oval, color = Lavender, style = filled]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
      tab6 [label = '@@6']
      tab7 [label = '@@7']
      tab8 [label = '@@8']
      tab9 [label = '@@9']
# set up node layout
      tab1 -> tab2;
      tab2 -> tab3;
      tab3 -> tab4;
      tab4 -> tab5;
      tab1 -> tab6;
      tab6 -> tab7;
      tab7 -> tab8;
      tab8 -> tab9
      }
[1]: 'Comparision Test: Pick b_n. Does sum b_n converge?'
      [2]: 'Yes'
      [3]: 'Is 0 greater than equal to a_n greater than equal to b_n'
      [4]: 'Yes'
      [5]: 'a_n converges'
      [6]: 'No'
      [7]: 'Is 0 greater than equal to b_n greater than equal to a_n'
      [8]: 'Yes'
      [9]: 'a_n diverges'
      ")
Plot_2
```
```{r}
Plot_3 <- grViz(diagram = "digraph flowchart {
      # define node aesthetics
      node [fontname = Arial, shape = oval, color = Lavender, style = filled]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
      tab6 [label = '@@6']
      tab7 [label = '@@7']
# set up node layout
      tab1 -> tab2;
      tab2 -> tab3;
      tab3 -> tab4;
      tab4 -> tab5;
      tab3 -> tab6;
      tab6 -> tab7
      }
[1]: 'Limit Comparision Test: Pick b_n. Does lim n to inf a_n/b_n = c >0 where a_n, b_n >0'
      [2]: 'Yes'
      [3]: 'Sum inf n=1 b_n converges?'
      [4]: 'Yes'
      [5]: 'sum a_n converges'
      [6]: 'No'
      [7]: 'Sum a_n diverges'
      ")
Plot_3
```

```{r}
Plot_4 <- grViz(diagram = "digraph flowchart {
      # define node aesthetics
      node [fontname = Arial, shape = oval, color = Lavender, style = filled]        
      tab1 [label = '@@1']
      tab2 [label = '@@2']
      tab3 [label = '@@3']
      tab4 [label = '@@4']
      tab5 [label = '@@5']
      tab6 [label = '@@6']
      tab7 [label = '@@7']
# set up node layout
      tab1 -> tab2;
      tab2 -> tab3;
      tab3 -> tab4;
      tab4 -> tab5;
      tab3 -> tab6;
      tab6 -> tab7
      }
[1]: 'Integral Test: Does a_n=f(x)? Is f(x) continuous, positive and decreasing on (a,inf)'
      [2]: 'Yes'
      [3]: 'Does integral a to inf converge'
      [4]: 'Yes'
      [5]: 'a_n converges'
      [6]: 'No'
      [7]: 'a_n diverges'
      ")
Plot_4
```

